[build]
  publish = "public" # The directory where Hugo outputs the generated site files
  command = "hugo"  # The command to build your site

[context.production.environment]
  HUGO_VERSION = "0.111.3"  # Use the Hugo version you're working with

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture"

